name: -FullStack tests (Angular + Spring)

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ“¦ Cache Angular node_modules
        uses: actions/cache@v3
        with:
          path: front/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: â˜• Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: ğŸ“¥ Try download Spring Boot JAR
        id: download-jar
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-jar
          path: back/target

      - name: ğŸ“¦ Install Angular
        working-directory: front
        run: |
          npm ci

      - name: â˜• Build Spring Boot JAR (if not downloaded)
        if: steps.download-jar.outcome != 'success'
        working-directory: back
        run: mvn clean install -DskipTests

      - name: â¬†ï¸ Upload Spring Boot JAR
        if: steps.download-jar.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: back/target/*.jar

      - name: ğŸš€ Start Spring Boot API
        run: |
          nohup java -jar back/target/*.jar &
          sleep 10

      - name: ğŸ§ª Run Angular tests with coverage
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: ./front

      - name: â˜• Run Java tests with coverage
        run: mvn test jacoco:report
        working-directory: ./back

      - name: ğŸ“¤ Upload Angular coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: angular-coverage-report
          path: front/coverage/

      - name: ğŸ“¤ Upload Java coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: java-coverage-report
          path: back/target/site/jacoco/